@StudyFlow.API_HostAddress = https://localhost:7123

GET {{StudyFlow.API_HostAddress}}/api/subjects

###

GET {{StudyFlow.API_HostAddress}}/api/subjects/1

###

POST {{StudyFlow.API_HostAddress}}/api/subjects
Content-Type: application/json

{
  "name": "Bases de datos"
}

###


GET {{StudyFlow.API_HostAddress}}/api/topics

###

POST {{StudyFlow.API_HostAddress}}/api/topics
Content-Type: application/json

{
  "name": "Postgressql",
  "subjectId": 3
}

###

@subjectId=1
GET {{StudyFlow.API_HostAddress}}/api/topics/by-subject/{{subjectId}}

###

@id=1
GET {{StudyFlow.API_HostAddress}}/api/topics/{{id}}

###







GET {{StudyFlow.API_HostAddress}}/api/study-notes

###

GET {{StudyFlow.API_HostAddress}}/api/study-notes/1

###

GET {{StudyFlow.API_HostAddress}}/api/study-notes/by-topic/1

###

POST {{StudyFlow.API_HostAddress}}/api/study-notes
Content-Type: application/json

{
  "name": "SELECT",
  "markdownText": "# SELECT\n\nSELECT sirve para consultar datos en SQL.",
  "topicId": 3
}
