import 'package:flutter/material.dart';
import 'package:frontend/data/example_data.dart';
import 'package:frontend/models/study_note.dart';
import 'package:frontend/models/topic.dart';
import 'package:frontend/screens/new_study_note.dart';
import 'package:frontend/screens/note_screen.dart';
import 'package:frontend/widgets/study_notes/study_note_list_item.dart';
import 'package:frontend/widgets/studyflow_screen_body.dart';
import 'package:google_fonts/google_fonts.dart';

class StudyNotesScreen extends StatefulWidget {
  const StudyNotesScreen({super.key, required this.topic});

  final Topic topic;

  @override
  State<StudyNotesScreen> createState() {
    return _StudyNotesScreenState();
  }
}

class _StudyNotesScreenState extends State<StudyNotesScreen> {
  final List<StudyNote> _studyNotes = [...exampleStudyNotes];

  void _openAddStudyNoteOverlay() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      useSafeArea: true,
      constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width),
      builder: (ctx) => NewStudyNote(onAddNote: _addStudyNote),
    );
  }

  void _addStudyNote(String title, String content) {
    // Simplified local ID generation for the current learning stage.
    // This solution is only intended for local example data and may create duplicate IDs if items are deleted.
    // In a later version, IDs will be generated by the backend or by a more robust local strategy.
    final newStudyNote = StudyNote(
      id: _studyNotes.length + 1,
      topicId: widget.topic.id,
      title: title,
      content: content,
    );

    setState(() {
      _studyNotes.add(newStudyNote);
    });

    ScaffoldMessenger.of(context).clearSnackBars();
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Note successfully created', textAlign: TextAlign.center),
      ),
    );
  }

  void _removeStudyNote(StudyNote note) {
    setState(() {
      _studyNotes.remove(note);
    });

    ScaffoldMessenger.of(context).clearSnackBars();

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Note deleted', textAlign: TextAlign.center),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final notes = _studyNotes.where((studyNote) {
      return studyNote.topicId == widget.topic.id;
    }).toList();

    Widget mainContent = const Center(
      child: Text('No notes found. Start adding some.'),
    );

    if (notes.isNotEmpty) {
      mainContent = ListView.builder(
        itemCount: notes.length,
        itemBuilder: (context, index) {
          final note = notes[index];

          return Dismissible(
            key: ValueKey(note.id),
            background: Container(
              color: Colors.red,
              alignment: Alignment.centerRight,
              padding: const EdgeInsets.only(right: 20),
              child: const Icon(Icons.delete, color: Colors.white),
            ),
            onDismissed: (direction) {
              _removeStudyNote(note);
            },
            child: StudyNoteListItem(
              note: note,
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => NoteScreen(note: note),
                  ),
                );
              },
            ),
          );
        },
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.topic.name),
        actions: [
          IconButton(
            onPressed: _openAddStudyNoteOverlay,
            icon: const Icon(Icons.add),
          ),
        ],
      ),
      body: StudyFlowScreenBody(
        child: Padding(
          padding: const EdgeInsets.only(top: 20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: Text(
                  'Notes',
                  style: GoogleFonts.inter(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                    color: Theme.of(context).colorScheme.onPrimaryContainer,
                  ),
                ),
              ),
              const SizedBox(height: 30),
              Expanded(child: mainContent),
            ],
          ),
        ),
      ),
    );
  }
}
