import 'package:flutter/material.dart';
import 'package:frontend/models/subject.dart';
import 'package:frontend/data/example_data.dart';
import 'package:frontend/screens/study_notes_screen.dart';
import 'package:frontend/models/topic.dart';
import 'package:frontend/screens/new_topic.dart';
import 'package:frontend/widgets/studyflow_screen_body.dart';
import 'package:google_fonts/google_fonts.dart';

class TopicsScreen extends StatefulWidget {
  const TopicsScreen({super.key, required this.subject});

  final Subject subject;

  @override
  State<TopicsScreen> createState() {
    return _TopicsScreenState();
  }
}

class _TopicsScreenState extends State<TopicsScreen> {
  final List<Topic> _topics = [...exampleTopics];

  void _openAddTopicOverlay() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      useSafeArea: true,
      constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width),
      builder: (ctx) => NewTopic(onAddTopic: _addTopic),
    );
  }

  void _addTopic(String name) {
    // Simplified local ID generation for the current learning stage.
    // This solution is only intended for local example data and may create duplicate IDs if items are deleted.
    // In a later version, IDs will be generated by the backend or by a more robust local strategy.

    final newTopic = Topic(
      id: _topics.length + 1,
      subjectId: widget.subject.id,
      name: name,
    );
    setState(() {
      _topics.add(newTopic);
    });

    ScaffoldMessenger.of(context).clearSnackBars();
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text(
          'Topic successfully created',
          textAlign: TextAlign.center,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final subjectTopics = _topics.where((topic) {
      return topic.subjectId == widget.subject.id;
    }).toList();

    Widget mainContent = const Center(
      child: Text('No topics found. Start adding some.'),
    );

    if (subjectTopics.isNotEmpty) {
      mainContent = ListView.builder(
        itemCount: subjectTopics.length,
        itemBuilder: (context, index) {
          final topic = subjectTopics[index];
          return Card(
            child: InkWell(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => StudyNotesScreen(topic: topic),
                  ),
                );
              },
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Row(
                  children: [
                    const Icon(Icons.topic),
                    const SizedBox(width: 12),
                    Text(topic.name),
                  ],
                ),
              ),
            ),
          );
        },
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.subject.name),
        actions: [
          IconButton(onPressed: _openAddTopicOverlay, icon: Icon(Icons.add)),
        ],
      ),
      body: StudyFlowScreenBody(
        child: Padding(
          padding: const EdgeInsets.only(top: 20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: Text(
                  'Topics',
                  style: GoogleFonts.inter(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                    color: Theme.of(context).colorScheme.onPrimaryContainer,
                  ),
                ),
              ),
              SizedBox(height: 30),
              Expanded(child: mainContent),
            ],
          ),
        ),
      ),
    );
  }
}
